apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-tracker
  namespace: fintech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-tracker
  template:
    metadata:
      labels:
        app: portfolio-tracker
    spec:
      serviceAccountName: app-sa
      containers:
      - name: portfolio-tracker
        image: mariamgbadamosi1/portfolio-tracker:latest           #CHANGE TO YOUR OWN <Ddocker_username>/portfolio-tracker:latest
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
