apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: fintech
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: fintech
  name: app-role
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: fintech
subjects:
- kind: ServiceAccount
  name: app-sa
  namespace: fintech
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io
